services:
  # MongoDB Database
  mongo:
    image: mongo:6
    container_name: dune-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: dune_forms
    volumes:
      - mongo_data:/data/db
      - ./dev/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - dune-network

  # Go Fiber API
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: development
    container_name: dune-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - MONGO_URI=mongodb://admin:password123@mongo:27017/dune_forms?authSource=admin
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - CORS_ORIGIN=http://localhost:3000
      - PORT=8080
    volumes:
      - ./apps/api:/app
      - /app/tmp
    depends_on:
      - mongo
    networks:
      - dune-network
    command: air -c .air.toml

  # Next.js Frontend
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: development
    container_name: dune-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - api
    networks:
      - dune-network
    command: npm run dev

volumes:
  mongo_data:

networks:
  dune-network:
    driver: bridge
