name: Backend

on:
  workflow_call:

jobs:
  format:
    name: Code Format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: apps/api/go.sum
    - name: Install tools
      run: make install-tools
    - name: Check code format
      run: make fmt-local

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: apps/api/go.sum
    - name: Install tools
      run: make install-tools
    - name: Run linting
      run: make lint-local

  test:
    name: Unit Tests and Code Coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: apps/api/go.sum
    - name: Run tests
      run: make test-local

  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: apps/api/go.sum
    - name: Build application
      run: make build-local
