name: CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/api/**'
      - '.github/workflows/**'

jobs:
  backend:
    name: Backend
    uses: ./.github/workflows/backend-ci.yml
